version: '3'

networks:
  default:
    name: web-mafia-bot
    external: true

services:
  web:
    build: .
    image: yiisoftware/yii2-php:7.4-fpm-nginx
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      #      - /etc/letsencrypt:/etc/letsencrypt
      - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock
      - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    ports:
      - '80:80'
      - '443:443'
  certbot:
    container_name: mafia-certbot
    image: certbot/certbot:latest
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
  db:
    image: mysql
    restart: always
    env_file:
      - ./.env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "./docker/mysql:/var/lib/mysql"
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8888:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db
